'''
Descriptive IRC server command responses, for code readability. Inspired by `status - HTTP Status for Humans`.

See RFC 1459: https://tools.ietf.org/html/rfc1459#section-6
See RFC 2812: https://tools.ietf.org/html/rfc2812#section-5
'''


def is_command(code: str) -> bool:
    return code in ALL


ADMIN = 'ADMIN'
AWAY = 'AWAY'
CNOTICE = 'CNOTICE'
CONNECT = 'CONNECT'
CPRIVMSG = 'CPRIVMSG'
DIE = 'DIE'
ENCAP = 'ENCAP'
ERROR = 'ERROR'
HELP = 'HELP'
INFO = 'INFO'
INVITE = 'INVITE'
ISON = 'ISON'
JOIN = 'JOIN'
KICK = 'KICK'
KILL = 'KILL'
KNOCK = 'KNOCK'
LINKS = 'LINKS'
LIST = 'LIST'
LUSERS = 'LUSERS'
MODE = 'MODE'
MOTD = 'MOTD'
NAMES = 'NAMES'
NAMESX = 'NAMESX'
NICK = 'NICK'
NOTICE = 'NOTICE'
OPER = 'OPER'
PART = 'PART'
PASS = 'PASS'
PING = 'PING'
PONG = 'PONG'
PRIVMSG = 'PRIVMSG'
QUIT = 'QUIT'
REHASH = 'REHASH'
RESTART = 'RESTART'
RULES = 'RULES'
SERVER = 'SERVER'
SERVICE = 'SERVICE'
SERVLIST = 'SERVLIST'
SETNAME = 'SETNAME'
SILENCE = 'SILENCE'
SQUERY = 'SQUERY'
SQUIT = 'SQUIT'
STATS = 'STATS'
SUMMON = 'SUMMON'
TIME = 'TIME'
TOPIC = 'TOPIC'
TRACE = 'TRACE'
UHNAMES = 'UHNAMES'
USER = 'USER'
USERHOST = 'USERHOST'
USERIP = 'USERIP'
USERS = 'USERS'
VERSION = 'VERSION'
WALLOPS = 'WALLOPS'
WATCH = 'WATCH'
WHO = 'WHO'
WHOIS = 'WHOIS'
WHOWAS = 'WHOWAS'


ALL = {
    ADMIN, AWAY, CNOTICE, CONNECT, CPRIVMSG, DIE, ENCAP, ERROR, HELP, INFO, INVITE, ISON, JOIN, KICK, KILL, KNOCK,
    LINKS, LIST, LUSERS, MODE, MOTD, NAMES, NAMESX, NICK, NOTICE, OPER, PART, PASS, PING, PONG, PRIVMSG, QUIT, REHASH,
    RESTART, RULES, SERVER, SERVICE, SERVLIST, SETNAME, SILENCE, SQUERY, SQUIT, STATS, SUMMON, TIME, TOPIC, TRACE,
    UHNAMES, USER, USERHOST, USERIP, USERS, VERSION, WALLOPS, WATCH, WHO, WHOIS, WHOWAS
}