'''
Descriptive IRC server numeric responses, for code readability. Inspired by `status - HTTP Status for Humans`.

Adapted from Freenode's source code, see below.

See RFC 1459: https://tools.ietf.org/html/rfc1459#section-6
See RFC 2812: https://tools.ietf.org/html/rfc2812#section-5
See Freenode: https://github.com/freenode/ircd-seven/blob/837efa08a938099c105d055abb67779d021d83e5/include/numeric.h
'''


RPL_WELCOME = '001'
RPL_YOURHOST = '002'
RPL_CREATED = '003'
RPL_MYINFO = '004'
RPL_ISUPPORT = '005'
RPL_SNOMASK = '008'
RPL_REDIR = '010'
RPL_MAP = '015'
RPL_MAPMORE = '016'
RPL_MAPEND = '017'
RPL_SAVENICK = '043'
RPL_TRACELINK = '200'
RPL_TRACECONNECTING = '201'
RPL_TRACEHANDSHAKE = '202'
RPL_TRACEUNKNOWN = '203'
RPL_TRACEOPERATOR = '204'
RPL_TRACEUSER = '205'
RPL_TRACESERVER = '206'
RPL_TRACENEWTYPE = '208'
RPL_TRACECLASS = '209'
RPL_STATSLINKINFO = '211'
RPL_STATSCOMMANDS = '212'
RPL_STATSCLINE = '213'
RPL_STATSNLINE = '214'
RPL_STATSILINE = '215'
RPL_STATSKLINE = '216'
RPL_STATSQLINE = '217'
RPL_STATSYLINE = '218'
RPL_ENDOFSTATS = '219'
RPL_STATSPLINE = '220'
RPL_UMODEIS = '221'
RPL_STATSFLINE = '224'
RPL_STATSDLINE = '225'
RPL_SERVLIST = '234'
RPL_SERVLISTEND = '235'
RPL_STATSLLINE = '241'
RPL_STATSUPTIME = '242'
RPL_STATSOLINE = '243'
RPL_STATSHLINE = '244'
RPL_STATSSLINE = '245'
RPL_STATSXLINE = '247'
RPL_STATSULINE = '248'
RPL_STATSDEBUG = '249'
RPL_STATSCONN = '250'
RPL_LUSERCLIENT = '251'
RPL_LUSEROP = '252'
RPL_LUSERUNKNOWN = '253'
RPL_LUSERCHANNELS = '254'
RPL_LUSERME = '255'
RPL_ADMINME = '256'
RPL_ADMINLOC1 = '257'
RPL_ADMINLOC2 = '258'
RPL_ADMINEMAIL = '259'
RPL_TRACELOG = '261'
RPL_ENDOFTRACE = '262'
RPL_LOAD2HI = '263'
RPL_LOCALUSERS = '265'
RPL_GLOBALUSERS = '266'
RPL_PRIVS = '270'
RPL_WHOISCERTFP = '276'
RPL_ACCEPTLIST = '281'
RPL_ENDOFACCEPT = '282'
RPL_NONE = '300'
RPL_AWAY = '301'
RPL_USERHOST = '302'
RPL_ISON = '303'
RPL_TEXT = '304'
RPL_UNAWAY = '305'
RPL_NOWAWAY = '306'
RPL_WHOISADMIN = '308'
RPL_WHOISUSER = '311'
RPL_WHOISSERVER = '312'
RPL_WHOISOPERATOR = '313'
RPL_WHOWASUSER = '314'
RPL_ENDOFWHOWAS = '369'
RPL_WHOISCHANOP = '316'
RPL_WHOISIDLE = '317'
RPL_ENDOFWHOIS = '318'
RPL_WHOISCHANNELS = '319'
RPL_WHOISSPECIAL = '320'
RPL_LISTSTART = '321'
RPL_LIST = '322'
RPL_LISTEND = '323'
RPL_CHANNELMODEIS = '324'
RPL_CHANNELMLOCK = '325'
RPL_CHANNELURL = '328'
RPL_CREATIONTIME = '329'
RPL_WHOISLOGGEDIN = '330'
RPL_NOTOPIC = '331'
RPL_TOPIC = '332'
RPL_TOPICWHOTIME = '333'
RPL_WHOISACTUALLY = '338'
RPL_INVITING = '341'
RPL_SUMMONING = '342'
RPL_INVITELIST = '346'
RPL_ENDOFINVITELIST = '347'
RPL_EXCEPTLIST = '348'
RPL_ENDOFEXCEPTLIST = '349'
RPL_VERSION = '351'
RPL_WHOREPLY = '352'
RPL_WHOSPCRPL = '354'
RPL_ENDOFWHO = '315'
RPL_NAMREPLY = '353'
RPL_WHOWASREAL = '360'
RPL_ENDOFNAMES = '366'
RPL_KILLDONE = '361'
RPL_CLOSING = '362'
RPL_CLOSEEND = '363'
RPL_LINKS = '364'
RPL_ENDOFLINKS = '365'
RPL_BANLIST = '367'
RPL_ENDOFBANLIST = '368'
RPL_INFO = '371'
RPL_MOTD = '372'
RPL_INFOSTART = '373'
RPL_ENDOFINFO = '374'
RPL_MOTDSTART = '375'
RPL_ENDOFMOTD = '376'
RPL_WHOISHOST = '378'
RPL_YOUREOPER = '381'
RPL_REHASHING = '382'
RPL_MYPORTIS = '384'
RPL_NOTOPERANYMORE = '385'
RPL_RSACHALLENGE = '386'
RPL_TIME = '391'
RPL_USERSSTART = '392'
RPL_USERS = '393'
RPL_ENDOFUSERS = '394'
RPL_NOUSERS = '395'
RPL_HOSTHIDDEN = '396'
ERR_NOSUCHNICK = '401'
ERR_NOSUCHSERVER = '402'
ERR_NOSUCHCHANNEL = '403'
ERR_CANNOTSENDTOCHAN = '404'
ERR_TOOMANYCHANNELS = '405'
ERR_WASNOSUCHNICK = '406'
ERR_TOOMANYTARGETS = '407'
ERR_NOORIGIN = '409'
ERR_INVALIDCAPCMD = '410'
ERR_NORECIPIENT = '411'
ERR_NOTEXTTOSEND = '412'
ERR_NOTOPLEVEL = '413'
ERR_WILDTOPLEVEL = '414'
ERR_TOOMANYMATCHES = '416'
ERR_UNKNOWNCOMMAND = '421'
ERR_NOMOTD = '422'
ERR_NOADMININFO = '423'
ERR_FILEERROR = '424'
ERR_NONICKNAMEGIVEN = '431'
ERR_ERRONEUSNICKNAME = '432'
ERR_NICKNAMEINUSE = '433'
ERR_BANNICKCHANGE = '435'
ERR_NICKCOLLISION = '436'
ERR_UNAVAILRESOURCE = '437'
ERR_NICKTOOFAST = '438'
ERR_SERVICESDOWN = '440'
ERR_USERNOTINCHANNEL = '441'
ERR_NOTONCHANNEL = '442'
ERR_USERONCHANNEL = '443'
ERR_NOLOGIN = '444'
ERR_SUMMONDISABLED = '445'
ERR_USERSDISABLED = '446'
ERR_NOTREGISTERED = '451'
ERR_ACCEPTFULL = '456'
ERR_ACCEPTEXIST = '457'
ERR_ACCEPTNOT = '458'
ERR_NEEDMOREPARAMS = '461'
ERR_ALREADYREGISTRED = '462'
ERR_NOPERMFORHOST = '463'
ERR_PASSWDMISMATCH = '464'
ERR_YOUREBANNEDCREEP = '465'
ERR_YOUWILLBEBANNED = '466'
ERR_KEYSET = '467'
ERR_LINKCHANNEL = '470'
ERR_CHANNELISFULL = '471'
ERR_UNKNOWNMODE = '472'
ERR_INVITEONLYCHAN = '473'
ERR_BANNEDFROMCHAN = '474'
ERR_BADCHANNELKEY = '475'
ERR_BADCHANMASK = '476'
ERR_NEEDREGGEDNICK = '477'
ERR_BANLISTFULL = '478'
ERR_BADCHANNAME = '479'
ERR_THROTTLE = '480'
ERR_NOPRIVILEGES = '481'
ERR_CHANOPRIVSNEEDED = '482'
ERR_CANTKILLSERVER = '483'
ERR_ISCHANSERVICE = '484'
ERR_RESTRICTED = '484'
ERR_BANNEDNICK = '485'
ERR_NONONREG = '486'
ERR_VOICENEEDED = '489'
ERR_NOOPERHOST = '491'
ERR_OWNMODE = '494'
ERR_UMODEUNKNOWNFLAG = '501'
ERR_USERSDONTMATCH = '502'
ERR_GHOSTEDCLIENT = '503'
ERR_USERNOTONSERV = '504'
ERR_WRONGPONG = '513'
ERR_DISABLED = '517'
ERR_HELPNOTFOUND = '524'
RPL_WHOISSECURE = '671'
RPL_MODLIST = '702'
RPL_ENDOFMODLIST = '703'
RPL_HELPSTART = '704'
RPL_HELPTXT = '705'
RPL_ENDOFHELP = '706'
ERR_TARGCHANGE = '707'
RPL_ETRACEFULL = '708'
RPL_ETRACE = '709'
RPL_KNOCK = '710'
RPL_KNOCKDLVR = '711'
ERR_TOOMANYKNOCK = '712'
ERR_CHANOPEN = '713'
ERR_KNOCKONCHAN = '714'
ERR_KNOCKDISABLED = '715'
ERR_TARGUMODEG = '716'
RPL_TARGNOTIFY = '717'
RPL_UMODEGMSG = '718'
RPL_OMOTDSTART = '720'
RPL_OMOTD = '721'
RPL_ENDOFOMOTD = '722'
ERR_NOPRIVS = '723'
RPL_TESTMASK = '724'
RPL_TESTLINE = '725'
RPL_NOTESTLINE = '726'
RPL_TESTMASKGECOS = '727'
RPL_QUIETLIST = '728'
RPL_ENDOFQUIETLIST = '729'
RPL_MONONLINE = '730'
RPL_MONOFFLINE = '731'
RPL_MONLIST = '732'
RPL_ENDOFMONLIST = '733'
ERR_MONLISTFULL = '734'
RPL_RSACHALLENGE2 = '740'
RPL_ENDOFRSACHALLENGE2 = '741'
ERR_MLOCKRESTRICTED = '742'
RPL_SCANMATCHED = '750'
RPL_SCANUMODES = '751'
RPL_LOGGEDIN = '900'
RPL_LOGGEDOUT = '901'
ERR_NICKLOCKED = '902'
RPL_SASLSUCCESS = '903'
ERR_SASLFAIL = '904'
ERR_SASLTOOLONG = '905'
ERR_SASLABORTED = '906'
ERR_SASLALREADY = '907'
ERR_LAST_ERR_MSG = '999'


ALL = {
    RPL_WELCOME, RPL_YOURHOST, RPL_CREATED, RPL_MYINFO, RPL_ISUPPORT, RPL_SNOMASK, RPL_REDIR, RPL_MAP, RPL_MAPMORE,
    RPL_MAPEND, RPL_SAVENICK, RPL_TRACELINK, RPL_TRACECONNECTING, RPL_TRACEHANDSHAKE, RPL_TRACEUNKNOWN,
    RPL_TRACEOPERATOR, RPL_TRACEUSER, RPL_TRACESERVER, RPL_TRACENEWTYPE, RPL_TRACECLASS, RPL_STATSLINKINFO,
    RPL_STATSCOMMANDS, RPL_STATSCLINE, RPL_STATSNLINE, RPL_STATSILINE, RPL_STATSKLINE, RPL_STATSQLINE, RPL_STATSYLINE,
    RPL_ENDOFSTATS, RPL_STATSPLINE, RPL_UMODEIS, RPL_STATSFLINE, RPL_STATSDLINE, RPL_SERVLIST, RPL_SERVLISTEND,
    RPL_STATSLLINE, RPL_STATSUPTIME, RPL_STATSOLINE, RPL_STATSHLINE, RPL_STATSSLINE, RPL_STATSXLINE, RPL_STATSULINE,
    RPL_STATSDEBUG, RPL_STATSCONN, RPL_LUSERCLIENT, RPL_LUSEROP, RPL_LUSERUNKNOWN, RPL_LUSERCHANNELS, RPL_LUSERME,
    RPL_ADMINME, RPL_ADMINLOC1, RPL_ADMINLOC2, RPL_ADMINEMAIL, RPL_TRACELOG, RPL_ENDOFTRACE, RPL_LOAD2HI,
    RPL_LOCALUSERS, RPL_GLOBALUSERS, RPL_PRIVS, RPL_WHOISCERTFP, RPL_ACCEPTLIST, RPL_ENDOFACCEPT, RPL_NONE, RPL_AWAY,
    RPL_USERHOST, RPL_ISON, RPL_TEXT, RPL_UNAWAY, RPL_NOWAWAY, RPL_WHOISADMIN, RPL_WHOISUSER, RPL_WHOISSERVER,
    RPL_WHOISOPERATOR, RPL_WHOWASUSER, RPL_ENDOFWHO, RPL_WHOISCHANOP, RPL_WHOISIDLE, RPL_ENDOFWHOIS, RPL_WHOISCHANNELS,
    RPL_WHOISSPECIAL, RPL_LISTSTART, RPL_LIST, RPL_LISTEND, RPL_CHANNELMODEIS, RPL_CHANNELMLOCK, RPL_CHANNELURL,
    RPL_CREATIONTIME, RPL_WHOISLOGGEDIN, RPL_NOTOPIC, RPL_TOPIC, RPL_TOPICWHOTIME, RPL_WHOISACTUALLY, RPL_INVITING,
    RPL_SUMMONING, RPL_INVITELIST, RPL_ENDOFINVITELIST, RPL_EXCEPTLIST, RPL_ENDOFEXCEPTLIST, RPL_VERSION, RPL_WHOREPLY,
    RPL_NAMREPLY, RPL_WHOSPCRPL, RPL_WHOWASREAL, RPL_KILLDONE, RPL_CLOSING, RPL_CLOSEEND, RPL_LINKS, RPL_ENDOFLINKS,
    RPL_ENDOFNAMES, RPL_BANLIST, RPL_ENDOFBANLIST, RPL_ENDOFWHOWAS, RPL_INFO, RPL_MOTD, RPL_INFOSTART, RPL_ENDOFINFO,
    RPL_MOTDSTART, RPL_ENDOFMOTD, RPL_WHOISHOST, RPL_YOUREOPER, RPL_REHASHING, RPL_MYPORTIS, RPL_NOTOPERANYMORE,
    RPL_RSACHALLENGE, RPL_TIME, RPL_USERSSTART, RPL_USERS, RPL_ENDOFUSERS, RPL_NOUSERS, RPL_HOSTHIDDEN, ERR_NOSUCHNICK,
    ERR_NOSUCHSERVER, ERR_NOSUCHCHANNEL, ERR_CANNOTSENDTOCHAN, ERR_TOOMANYCHANNELS, ERR_WASNOSUCHNICK,
    ERR_TOOMANYTARGETS, ERR_NOORIGIN, ERR_INVALIDCAPCMD, ERR_NORECIPIENT, ERR_NOTEXTTOSEND, ERR_NOTOPLEVEL,
    ERR_WILDTOPLEVEL, ERR_TOOMANYMATCHES, ERR_UNKNOWNCOMMAND, ERR_NOMOTD, ERR_NOADMININFO, ERR_FILEERROR,
    ERR_NONICKNAMEGIVEN, ERR_ERRONEUSNICKNAME, ERR_NICKNAMEINUSE, ERR_BANNICKCHANGE, ERR_NICKCOLLISION,
    ERR_UNAVAILRESOURCE, ERR_NICKTOOFAST, ERR_SERVICESDOWN, ERR_USERNOTINCHANNEL, ERR_NOTONCHANNEL, ERR_USERONCHANNEL,
    ERR_NOLOGIN, ERR_SUMMONDISABLED, ERR_USERSDISABLED, ERR_NOTREGISTERED, ERR_ACCEPTFULL, ERR_ACCEPTEXIST,
    ERR_ACCEPTNOT, ERR_NEEDMOREPARAMS, ERR_ALREADYREGISTRED, ERR_NOPERMFORHOST, ERR_PASSWDMISMATCH,
    ERR_YOUREBANNEDCREEP, ERR_YOUWILLBEBANNED, ERR_KEYSET, ERR_LINKCHANNEL, ERR_CHANNELISFULL, ERR_UNKNOWNMODE,
    ERR_INVITEONLYCHAN, ERR_BANNEDFROMCHAN, ERR_BADCHANNELKEY, ERR_BADCHANMASK, ERR_NEEDREGGEDNICK, ERR_BANLISTFULL,
    ERR_BADCHANNAME, ERR_THROTTLE, ERR_NOPRIVILEGES, ERR_CHANOPRIVSNEEDED, ERR_CANTKILLSERVER, ERR_RESTRICTED,
    ERR_ISCHANSERVICE, ERR_BANNEDNICK, ERR_NONONREG, ERR_VOICENEEDED, ERR_NOOPERHOST, ERR_OWNMODE, ERR_UMODEUNKNOWNFLAG,
    ERR_USERSDONTMATCH, ERR_GHOSTEDCLIENT, ERR_USERNOTONSERV, ERR_WRONGPONG, ERR_DISABLED, ERR_HELPNOTFOUND,
    RPL_WHOISSECURE, RPL_MODLIST, RPL_ENDOFMODLIST, RPL_HELPSTART, RPL_HELPTXT, RPL_ENDOFHELP, ERR_TARGCHANGE,
    RPL_ETRACEFULL, RPL_ETRACE, RPL_KNOCK, RPL_KNOCKDLVR, ERR_TOOMANYKNOCK, ERR_CHANOPEN, ERR_KNOCKONCHAN,
    ERR_KNOCKDISABLED, ERR_TARGUMODEG, RPL_TARGNOTIFY, RPL_UMODEGMSG, RPL_OMOTDSTART, RPL_OMOTD, RPL_ENDOFOMOTD,
    ERR_NOPRIVS, RPL_TESTMASK, RPL_TESTLINE, RPL_NOTESTLINE, RPL_TESTMASKGECOS, RPL_QUIETLIST, RPL_ENDOFQUIETLIST,
    RPL_MONONLINE, RPL_MONOFFLINE, RPL_MONLIST, RPL_ENDOFMONLIST, ERR_MONLISTFULL, RPL_RSACHALLENGE2,
    RPL_ENDOFRSACHALLENGE2, ERR_MLOCKRESTRICTED, RPL_SCANMATCHED, RPL_SCANUMODES, RPL_LOGGEDIN, RPL_LOGGEDOUT,
    ERR_NICKLOCKED, RPL_SASLSUCCESS, ERR_SASLFAIL, ERR_SASLTOOLONG, ERR_SASLABORTED, ERR_SASLALREADY, ERR_LAST_ERR_MSG
}


if __name__ == '__main__':
    import textwrap

    INDENT = '    '

    replies = [(key, value) for key, value in locals().items() if key.startswith('RPL') or key.startswith('ERR')]

    all = ', '.join(key for key, value in sorted(replies, key=lambda pair: pair[1]))

    for line in textwrap.wrap(all, width=120 - len(INDENT)):
        print(INDENT, line, sep='')